[tool.ruff.format]
# Enable preview style formatting.
quote-style = "preserve"

[tool.vulture]
ignore_decorators = ["@task"]
ignore_names = ["test_*", "Test*"]
paths = ["tasks"]

[tool.mypy]
strict = true
strict_equality = true
python_version = "3.10"
# Follows imports and type-check imported modules.
follow_imports = "normal"
# Ignore errors about imported packages that don't provide type hints.
ignore_missing_imports = true
# Don't require that all functions be annotated, as it would create
# a lot of noise for imported modules that aren't annotated yet.
# Note that this is the default behavior, but we're making our choice explicit here.
disallow_untyped_defs = false
# Include column numbers in errors.
show_column_numbers = true
files = ['tasks/kernel.py']
disable_error_code = [
]
